proxychains appcfg.py --application csrgxtua-01 update crawler-slave/
proxychains appcfg.py --application csrgxtua-02 update crawler-slave/
proxychains appcfg.py --application csrgxtua-03 update crawler-slave/
proxychains appcfg.py --application csrgxtua-04 update crawler-slave/
proxychains appcfg.py --application csrgxtua-05 update crawler-slave/
proxychains appcfg.py --application csrgxtua-06 update crawler-slave/
proxychains appcfg.py --application csrgxtua-07 update crawler-slave/
proxychains appcfg.py --application csrgxtua-08 update crawler-slave/
proxychains appcfg.py --application csrgxtua-09 update crawler-slave/
proxychains appcfg.py --application csrgxtua-10 update crawler-slave/
proxychains appcfg.py --application csrgxtua-11 update crawler-slave/
proxychains appcfg.py --application csrgxtua-12 update crawler-slave/
proxychains appcfg.py --application csrgxtua-13 update crawler-slave/
proxychains appcfg.py --application csrgxtua-14 update crawler-slave/
proxychains appcfg.py --application csrgxtua-15 update crawler-slave/
proxychains appcfg.py --application csrgxtua-16 update crawler-slave/
proxychains appcfg.py --application csrgxtua-17 update crawler-slave/
proxychains appcfg.py --application csrgxtua-18 update crawler-slave/
proxychains appcfg.py --application csrgxtua-19 update crawler-slave/
proxychains appcfg.py --application csrgxtua-20 update crawler-slave/
proxychains appcfg.py --application csrgxtua-21 update crawler-slave/
proxychains appcfg.py --application csrgxtua-22 update crawler-slave/
proxychains appcfg.py --application csrgxtua-23 update crawler-slave/
proxychains appcfg.py --application csrgxtua-24 update crawler-slave/
proxychains appcfg.py --application csrgxtua-25 update crawler-slave/
