proxychains appcfg.py --application csrgxtu01 update crawler-slave/
proxychains appcfg.py --application csrgxtu02 update crawler-slave/
proxychains appcfg.py --application csrgxtu03 update crawler-slave/
proxychains appcfg.py --application csrgxtu04 update crawler-slave/
proxychains appcfg.py --application csrgxtu05 update crawler-slave/
proxychains appcfg.py --application csrgxtu06 update crawler-slave/
proxychains appcfg.py --application csrgxtu07 update crawler-slave/
proxychains appcfg.py --application csrgxtu08 update crawler-slave/
proxychains appcfg.py --application csrgxtu09 update crawler-slave/
proxychains appcfg.py --application csrgxtu10 update crawler-slave/
proxychains appcfg.py --application csrgxtu11 update crawler-slave/
proxychains appcfg.py --application csrgxtu12 update crawler-slave/
proxychains appcfg.py --application csrgxtu13 update crawler-slave/
proxychains appcfg.py --application csrgxtu14 update crawler-slave/
proxychains appcfg.py --application csrgxtu15 update crawler-slave/
proxychains appcfg.py --application csrgxtu16 update crawler-slave/
proxychains appcfg.py --application csrgxtu17 update crawler-slave/
proxychains appcfg.py --application csrgxtu18 update crawler-slave/
proxychains appcfg.py --application csrgxtu19 update crawler-slave/
proxychains appcfg.py --application csrgxtu20 update crawler-slave/
proxychains appcfg.py --application csrgxtu21 update crawler-slave/
proxychains appcfg.py --application csrgxtu22 update crawler-slave/
proxychains appcfg.py --application csrgxtu23 update crawler-slave/
proxychains appcfg.py --application csrgxtu24 update crawler-slave/
